---
# This playbook contains plays to install and maintain cjdcmd.

- name: create the cjdcmd build directory
  file: state=directory path="{{ package_build_dir }}/cjdcmd-git"
    owner=root group=users mode=0775

- name: create the cjdcmd pkgbuild file
  copy: src=cjdcmd-git.PKGBUILD dest="{{ package_build_dir }}/cjdcmd-git/PKGBUILD"
    owner=root group=users mode=0664

- name: build and install cjdcmd from git
  command: /usr/local/bin/update-cjdns cjdcmd-git
  register: update_cjdcmd
  changed_when: "update_cjdcmd.stderr.find('WARNING: A package has already been built') == -1"
  notify: clean up older cjdns-related packages

- name: configure the cjdcmd tool
  command: /usr/bin/cjdcmd cjdnsadmin --file /etc/cjdroute.conf creates=/root/.cjdnsadmin
  notify: copy the cjdcmd config file to the admin user's home directory
