---
# This playbook handles cjdns notifications.

- name: restart the cjdns daemon
  service: name=cjdns state=restarted

- name: clean up older cjdns-related packages
  command: find "{{ package_build_dir }}" -maxdepth 2 -type f -name "cjd*-git-*.pkg.tar.xz" -mtime +28 -print -delete
  register: clean_up_cjdns_packages
  changed_when: clean_up_cjdns_packages.stdout.find('pkg.tar.xz') != -1

- name: copy the cjdcmd config file to the admin user's home directory
  command: install --preserve-timestamps --owner="{{ admin_user }}" --group=users --mode=0600 /root/.cjdnsadmin "/home/{{ admin_user }}/.cjdnsadmin"
